name: CI Pipeline

on:
  push:
    branches:
      - feature/analysis
      - develop
  pull_request:
    types: [opened, edited, reopened, synchronize, review_requested, submitted]
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --logger "trx;LogFileName=report.xml"

  review-check:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check reviews
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const {data: reviews} = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            const approved = reviews.some(review => review.state === 'APPROVED');
            if (!approved) {
              core.setFailed("Код-рев’ю не схвалено");
            }
  
  metrics-and-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Count lines of code with Cloc
        run: |
          sudo apt-get install -y cloc
          cloc . > cloc-report.txt
          cat cloc-report.txt

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # 1. Встановлюємо сканер для .NET
          dotnet tool install --global dotnet-sonarscanner
          
          # 2. Автоматично знаходимо файл рішення (.sln)
          SLN_PATH=$(find . -name "*.sln" | head -n 1)
          echo "Found solution at: $SLN_PATH"
          
          # 3. ПОЧАТОК АНАЛІЗУ (Твої параметри тут)
          # /k: - це твій projectKey
          # /d:sonar.host.url - це твій сервер
          dotnet-sonarscanner begin /k:"Dortmo0nd_Places_Lab5" /o:"dortmo0nd" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          
          # 4. ОБОВ'ЯЗКОВИЙ БІЛД (без нього Sonar не побачить код C#)
          dotnet build "$SLN_PATH" --configuration Release
          
          # 5. ЗАВЕРШЕННЯ АНАЛІЗУ (відправка даних на сервер)
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
